services:
  - type: web
    name: rksolutions-backend
    runtime: docker
    plan: free
    healthCheckPath: /v3/api-docs
    autoDeploy: true
    envVars:
      - key: JAVA_VERSION
        value: "21"
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        value: "rksolutions_super_secret_key_2024_change_in_production_environment_minimum_256_bits"
      - key: MAIL_USERNAME
        value: ""
      - key: MAIL_PASSWORD
        value: ""
    disk:
      name: rksolutions-data
      mountPath: /data
      sizeGB: 1
